### ISSUE TITLE
[BUG REPORT]: Upload to this timeseries 404

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/instrumentation#116]
### https://develop-midas.rsgis.dev testing

Attempting to upload data for a specific instrument from the instrument's page. Selecting the timeseries and `Upload to this timeseries` button results in the 404 error shown below.

## Steps To Reproduce
1. Go to a project - used __Nashville District Streamgages__
2. Click on `All Instruments` and select an instrument - used  __NAST1-CumberlandR-NashvilleTN__
3. Select `Timeseries` tab
4. Select any timeseries, with or without data
5. Click `Upload to this timeseries`

## Expected behavior
`Uploader` made available with `Import As` with `Timeseries Measurement` already selected

## Actual behavior
404 Not found page

## Screenshots
![image](https://user-images.githubusercontent.com/37386268/117827642-c8b1b680-b236-11eb-8a98-91046f141042.png)

## Desktop (please complete the following information):
 - OS: Win10
 - Browser: Microsoft Edge
 - Version: 90.0.818.56

## Smartphone (please complete the following information):
NA

## Additional context
No additional context

**Comment by KevinJJackson** [comment]
I can fix the 404, I don't think there was ever behavior in place to auto select Measurements from the settings though... especially since that field isn't even rendered until the user has a file selected. I'd think if we wanted to add that functionality we'd want to open a new issue for that specifically.
